In [1]:
import pandas as pd

In [2]:
question_only_df = pd.read_csv('part1.csv')
question_only_df

Index  Bhanu  Swarna  Sampath  Tanmay
0       1      1       1        1       1
1       2      3       3        3       3
2       3      1       1        3       1
3       4      3       3        3       3
4       5      3       3        0       0
5       6      3       2        3       3
6       7      1       0        0       1
7       8      4       1        4       2
8       9      0       0        0       2
9      10      1       1        1       1
10     11      2       4        2       2
11     12      0       0        0       0
12     13      1       0        2       2
13     14      4       3        2       3
14     15      3       3        3       0

In [3]:
question_and_frame_df = pd.read_csv('part2and3.csv')
question_and_frame_df

Index  Bhanu Answer  Bhanu Frame  Swarna Answer  Swarna Frame  \
0       1             2            1              0             1   
1       1             1            1              2             0   
2       1             1            0              1             1   
3       1             4            0              2             1   
4       1             1            0              1             0   
5       1             0            1              0             1   
6       1             0            0              0             1   
7       1             1            1              1             1   
8       1             0            0              0             0   
9       1             2            0              2             0   
10      1             0            1              4             0   
11      1             2            1              2             0   
12      1             1            0              0             1   
13      1             4            1              3             0   
14      1             1            1              1             1   

    Sampath Answer  Sampath Frame  Tanmay Answer  Tanmay Frame  
0                2              1              0             1  
1                0              0              1             0  
2                1              1              1             1  
3                2              1              2             1  
4                4              0              1             1  
5                0              1              0             0  
6                0              1              0             1  
7                1              1              1             1  
8                0              0              2             1  
9                2              0              2             1  
10               4              0              4             0  
11               2              1              2             1  
12               0              0              0             0  
13               4              1              4             0  
14               2              1              1             1

In [6]:
!conda install -c conda-forge statsmodels -y

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.11.0
  latest version: 22.9.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /opt/homebrew/Caskroom/miniforge/base/envs/viz

  added / updated specs:
    - statsmodels


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    patsy-0.5.2                |     pyhd8ed1ab_0         188 KB  conda-forge
    statsmodels-0.13.2         |   py39h7b9fbcb_0        10.5 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        10.7 MB

The following NEW packages will be INSTALLED:

  patsy              conda-forge/noarch::patsy-0.5.2-pyhd8ed1ab_0
  scipy              conda-forge/osx-arm64::scipy-1.9.1-py39h737da60_0
  statsmodels        conda-forge/osx-arm64::statsm

In [7]:
from statsmodels import stats 

In [29]:
arr = question_only_df.iloc[:, 1:].to_numpy()
arr

array([[1, 1, 1, 1],
       [3, 3, 3, 3],
       [1, 1, 3, 1],
       [3, 3, 3, 3],
       [3, 3, 0, 0],
       [3, 2, 3, 3],
       [1, 0, 0, 1],
       [4, 1, 4, 2],
       [0, 0, 0, 2],
       [1, 1, 1, 1],
       [2, 4, 2, 2],
       [0, 0, 0, 0],
       [1, 0, 2, 2],
       [4, 3, 2, 3],
       [3, 3, 3, 0]])

In [30]:
from statsmodels.stats.inter_rater import aggregate_raters, fleiss_kappa

In [33]:
aggr = aggregate_raters(arr)
aggr

(array([[0, 4, 0, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 3, 0, 1, 0],
        [0, 0, 0, 4, 0],
        [2, 0, 0, 2, 0],
        [0, 0, 1, 3, 0],
        [2, 2, 0, 0, 0],
        [0, 1, 1, 0, 2],
        [3, 0, 1, 0, 0],
        [0, 4, 0, 0, 0],
        [0, 0, 3, 0, 1],
        [4, 0, 0, 0, 0],
        [1, 1, 2, 0, 0],
        [0, 0, 1, 2, 1],
        [1, 0, 0, 3, 0]]),
 array([0, 1, 2, 3, 4]))

In [41]:
fleiss_kappa(table=aggr[0], method='fleiss')

0.4468704512372634

In [42]:
video_question_df = question_and_frame_df[["Bhanu Answer", "Swarna Answer", "Sampath Answer", "Tanmay Answer"]]
video_question_df

Bhanu Answer  Swarna Answer  Sampath Answer  Tanmay Answer
0              2              0               2              0
1              1              2               0              1
2              1              1               1              1
3              4              2               2              2
4              1              1               4              1
5              0              0               0              0
6              0              0               0              0
7              1              1               1              1
8              0              0               0              2
9              2              2               2              2
10             0              4               4              4
11             2              2               2              2
12             1              0               0              0
13             4              3               4              4
14             1              1               2              1

In [43]:
arr = video_question_df.iloc[:, 1:].to_numpy()
arr

array([[0, 2, 0],
       [2, 0, 1],
       [1, 1, 1],
       [2, 2, 2],
       [1, 4, 1],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [0, 0, 2],
       [2, 2, 2],
       [4, 4, 4],
       [2, 2, 2],
       [0, 0, 0],
       [3, 4, 4],
       [1, 2, 1]])

In [44]:
aggr = aggregate_raters(arr)
aggr

(array([[2, 0, 1, 0, 0],
        [1, 1, 1, 0, 0],
        [0, 3, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 2, 0, 0, 1],
        [3, 0, 0, 0, 0],
        [3, 0, 0, 0, 0],
        [0, 3, 0, 0, 0],
        [2, 0, 1, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 0, 3],
        [0, 0, 3, 0, 0],
        [3, 0, 0, 0, 0],
        [0, 0, 0, 1, 2],
        [0, 2, 1, 0, 0]]),
 array([0, 1, 2, 3, 4]))

In [45]:
fleiss_kappa(table=aggr[0], method='fleiss')

0.6105193075898803

In [47]:
single_frame_df = question_and_frame_df[["Bhanu Frame", "Swarna Frame", "Sampath Frame", "Tanmay Frame"]]
single_frame_df

Bhanu Frame  Swarna Frame  Sampath Frame  Tanmay Frame
0             1             1              1             1
1             1             0              0             0
2             0             1              1             1
3             0             1              1             1
4             0             0              0             1
5             1             1              1             0
6             0             1              1             1
7             1             1              1             1
8             0             0              0             1
9             0             0              0             1
10            1             0              0             0
11            1             0              1             1
12            0             1              0             0
13            1             0              1             0
14            1             1              1             1

In [51]:
arr = single_frame_df.to_numpy()
arr

array([[1, 1, 1, 1],
       [1, 0, 0, 0],
       [0, 1, 1, 1],
       [0, 1, 1, 1],
       [0, 0, 0, 1],
       [1, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 1, 1]])

In [52]:
fleiss_kappa(table=aggr[0], method='fleiss')

0.6105193075898803